// layouts/RootLayout.js
import React from "react";
import "./globals.css"; // Import other global styles

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" integrity="sha512-FVzgOFJxPpABJIL7jOBcPih7gvziIF4jKy9xtKTbO3qYBtQ03fhbybITvEkj0Q+6PYLvcNviIwWv1eH5eT7tQw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        {/* Include other external stylesheets if necessary */}
      </head>
      <body className="bg-green-50 min-h-screen flex flex-col items-center justify-center bg-left bg-right">
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
